apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tr2aw7pgs-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tr2aw7pgs-java-quarkus-gitops